"""Export LSS specs to runnable implementation stubs."""

from __future__ import annotations

from pathlib import Path
from typing import Any

import yaml

GENERIC_RUN_PY = '''#!/usr/bin/env python3
"""Generated stub — run loop from LSS spec via generic loop_runtime."""

from __future__ import annotations

import argparse
import json
import sys
from pathlib import Path

ROOT = Path(__file__).resolve()
for _ in range(8):
    if (ROOT / "implementations" / "generic").is_dir():
        break
    ROOT = ROOT.parent
else:
    raise SystemExit("Could not locate repo root (implementations/generic)")
sys.path.insert(0, str(ROOT / "implementations" / "generic"))

from loop_runtime import LoopRuntime, MockLLM, load_lss_spec  # noqa: E402

SPEC = Path(__file__).resolve().parent / "spec.yaml"


def main() -> int:
    parser = argparse.ArgumentParser(description="Run {loop_name}")
    parser.add_argument("--spec", type=Path, default=SPEC)
    parser.add_argument("--input", default="Complete the declared loop objective")
    parser.add_argument("--json", action="store_true")
    args = parser.parse_args()

    spec = load_lss_spec(args.spec)
    runtime = LoopRuntime(spec, llm=MockLLM(seed=spec.get("loop_name", "loop")))
    result = runtime.run(args.input)
    payload = {{
        "loop_name": spec.get("loop_name"),
        "success": result.success,
        "iterations": result.iterations,
        "quality_score": result.quality_score,
        "termination_reason": result.termination_reason,
        "output": result.output,
    }}
    if args.json:
        print(json.dumps(payload, indent=2))
    else:
        print(f"Success={{result.success}} iterations={{result.iterations}} score={{result.quality_score:.2f}}")
    return 0 if result.success else 1


if __name__ == "__main__":
    raise SystemExit(main())
'''

LANGGRAPH_RUN_PY = '''#!/usr/bin/env python3
"""Generated LangGraph stub for {loop_name}."""

from __future__ import annotations

import sys
from pathlib import Path

ROOT = Path(__file__).resolve()
for _ in range(8):
    if (ROOT / "implementations" / "langgraph").is_dir():
        break
    ROOT = ROOT.parent
else:
    raise SystemExit("Could not locate repo root (implementations/langgraph)")
sys.path.insert(0, str(ROOT / "implementations" / "langgraph"))

from reflection_graph import build_reflection_graph, run_reflection_graph  # noqa: E402


def main() -> int:
    graph = build_reflection_graph()
    result = run_reflection_graph(
        graph,
        objective="{objective_short}",
        task="Complete the declared loop objective",
        quality_threshold=0.75,
        max_iterations=3,
    )
    print(f"success={{result.success}} iterations={{result.iterations}} score={{result.quality_score:.2f}}")
    return 0 if result.success else 1


if __name__ == "__main__":
    raise SystemExit(main())
'''

CREWAI_RUN_PY = '''#!/usr/bin/env python3
"""Generated CrewAI stub for {loop_name}."""

from __future__ import annotations

import subprocess
import sys
from pathlib import Path

ROOT = Path(__file__).resolve()
for _ in range(8):
    if (ROOT / "implementations" / "crewai").is_dir():
        break
    ROOT = ROOT.parent
else:
    raise SystemExit("Could not locate repo root (implementations/crewai)")


def main() -> int:
    bridge = ROOT / "implementations" / "crewai" / "run.py"
    return subprocess.call([sys.executable, str(bridge)])


if __name__ == "__main__":
    raise SystemExit(main())
'''

README_TEMPLATE = """# {loop_name}

Generated by LoopForge export (`{target}`).

## Run

```bash
python run.py
python run.py --json
```

Spec: `spec.yaml` (copied from source LSS).

Workers in spec: {workers}
"""


def load_spec(path: Path) -> dict[str, Any]:
    with path.open(encoding="utf-8") as fh:
        data = yaml.safe_load(fh)
    if not isinstance(data, dict):
        raise ValueError(f"Invalid spec: {path}")
    return data


def export_stub(spec_path: Path, out_dir: Path, target: str) -> Path:
    spec = load_spec(spec_path)
    loop_name = spec.get("loop_name", spec_path.stem)
    objective = str(spec.get("objective", "")).split("\n")[0][:120]
    workers = ", ".join(w.get("id", "?") for w in (spec.get("workers") or []))

    out_dir.mkdir(parents=True, exist_ok=True)
    (out_dir / "spec.yaml").write_text(spec_path.read_text(encoding="utf-8"), encoding="utf-8")

    if target == "generic":
        run_src = GENERIC_RUN_PY.format(loop_name=loop_name)
    elif target == "langgraph":
        run_src = LANGGRAPH_RUN_PY.format(loop_name=loop_name, objective_short=objective.replace('"', "'"))
    elif target == "crewai":
        run_src = CREWAI_RUN_PY.format(loop_name=loop_name)
    else:
        raise ValueError(f"Unknown export target: {target}")

    (out_dir / "run.py").write_text(run_src, encoding="utf-8")
    (out_dir / "README.md").write_text(
        README_TEMPLATE.format(loop_name=loop_name, target=target, workers=workers or "none"),
        encoding="utf-8",
    )
    return out_dir
